### ISSUE TITLE
deprecated options in chronyd config template

### ISSUE THREAD

**Issue by combrs** [ericsysmin/ansible-role-chrony#3]
in template
````
# Specify the key used as password for chronyc.
commandkey 1
# Generate command key if missing.
generatecommandkey
````

cannot find it in man, and there is mentions in log
````
мар 27 10:47:05 chronyd[85851]: commandkey directive is no longer supported
мар 27 10:47:05 chronyd[85851]: generatecommandkey directive is no longer supported
````

Also this parameters are in doubt
````
bindcmdaddress 127.0.0.1
bindcmdaddress ::1
````

in man
> By default, chronyd binds to the loopback interface (with addresses 127.0.0.1 and ::1). This blocks all access except from localhost.

I suppose to delete all this parameters from template as deprecated.

**Comment by ericsysmin** [comment]
@combrs can you make a PR?

**Comment by retr0h** [comment]
@ericsysmin ^ done
